version: "3"
services:
  app:
    build: .
    command: node ./project/dist/app.js
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    ports:
      - "8081:4000"
    volumes:
      - .:/app
      - ./node_modules:/home/nodejs/node_modules
      - ./project/.env:/app/.env
  nginx:
    image: nginx:latest
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_USERNAME: ws
      MONGO_INITDB_PASSWORD: password
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: sample_db

volumes:
  mongodb-data:
  postgres-data: